# Generated by Django 2.0.6 on 2018-07-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
