# Generated by Django 2.0.6 on 2018-07-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscategory_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='nums',
            field=models.IntegerField(null=True),
        ),
    ]
