# Generated by Django 2.0.6 on 2018-07-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
