# Generated by Django 2.0.6 on 2018-07-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('nums', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
