# Generated by Django 2.0.6 on 2018-08-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_url', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('link_url', models.CharField(max_length=50)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
