# Generated by Django 2.0.6 on 2018-08-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminte', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.CharField(max_length=200),
        ),
    ]
