# Generated by Django 2.0.6 on 2018-08-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminte', '0004_banner_is_del'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['position']},
        ),
    ]
